name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
          repository: santhoshn16/FoodDeliveryServer
          ref: main

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Maven
      run: |
          cd /home/runner/work/FoodDeliveryServer/FoodDeliveryServer/spring-security/spring-security/        
          mvn package

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVPRIV}}
      run: |
        ssh ec2-user@54.175.99.206 "sudo /home/ec2-user/script.sh"


